### ISSUE TITLE
City names is null for some IP's

### ISSUE THREAD

**Issue by nagpals** [maxmind/GeoIP2-java#104]
Hi,
It has been observed that we don't get city name while searching for an IP, though asn or country information is available. When the same IP is searched among other ip data sources, we get the result back. 
Can someone guide me, what is the issue .
I don't want to mark it as an issue but just a query to the group. 

Regards,
Hemant Nagpal

**Comment by nchelluri** [comment]
HI @nagpals, we do not have city (or any other particular field) for every IP address.

If you have corrections to our data, you can submit them to https://support.maxmind.com/geoip-data-correction-request/ .

Thanks!

**Comment by hemantvuliv** [comment]
Ok , Appreciate your prompt response. 

Thanks,
