### ISSUE TITLE
Resolving continent from "represented country"

### ISSUE THREAD

**Issue by eiden** [maxmind/GeoIP2-java#106]
From: https://dev.maxmind.com/geoip/geoip2/whats-new-in-geoip2/

> Finally, we also include a represented_country key for some records. This is used when the IP address belongs to something like a military base. The represented_country is the country that the base represents. This can be useful for managing content licensing, among other uses.

I did a quick test using the GeoLite2-Country database.
When testing with IP `82.205.224.220` I get:

```
CountryResponse response = lookup("82.205.224.220");

response.getCountry().getIsoCode() -> AE 
response.getRegisteredCountry().getIsoCode() -> AE 
response.getRepresentedCountry().getIsoCode() -> US 
response.getContinent().getCode() -> AS 
```
Seems like the continent is resolved based on the country. 
Is there no way to retrieve the correct continent for the "represented country"?

It might make more sense to get the continent from the `Country`?, something like this: 
```
response.getCountry().getContinent()
response.getRegisteredCountry().getContinent()
response.getRepresentedCountry().getContinent()
```

**Comment by oschwald** [comment]
That is correct. The database only contains the continent, city, and postal code for the IP geolocation country. It does not contain the continent for the registered country or the represented country; that data is not in the database. This is not specific to this API as the data is stored in the database, not the API. If you have further data questions, please email [support@maxmind.com](mailto:support@maxmind.com).
