### ISSUE TITLE
GeoIP2-City DB: InvalidDatabaseException 

### ISSUE THREAD

**Issue by fabiocognigni** [maxmind/GeoIP2-java#109]
I've been successfully using this library (v2.12.0) with the GeoLite2-City DB. I now want to move to use the GeoIP2-City DB instead but I'm getting the below error even using exactly the same code:
```
com.maxmind.db.InvalidDatabaseException: The MaxMind DB file's search tree is corrupt: contains pointer larger than the database.
   at com.maxmind.db.Reader.resolveDataPointer(Reader.java:243)
   at com.maxmind.db.Reader.get(Reader.java:150)
   at com.maxmind.geoip2.DatabaseReader.get(DatabaseReader.java:182)
   at com.maxmind.geoip2.DatabaseReader.city(DatabaseReader.java:233)
```

https://github.com/maxmind/GeoIP2-java/issues/32 is on the same topic but that doesn't seem my same case: my Scala app is built using sbt and doesn't run as a Jar. It resolves the mmdb file from a local relative path and finding the file doesn't seem to be the problem (if I try changing the file name I get correctly an error like "java.io.FileNotFoundException: db/GeoIP2-CityXX.mmdb").

Below there is the snippet of code I'm using and literally what changed is just the mmdb file so I tend to think something is wrong with the content of that file or with the geoip2 Jar accessing it: I noticed that the GeoIP2-City file is much bigger (~130MB) than the GeoLite2-City one (~50MB) but it doesn't seem to be corrupted.

All I did to install the file for the application was:
1. `wget -O GeoIP2-City.mmdb.gz 'https://download.maxmind.com/app/geoip_download?edition_id=GeoIP2-City&suffix=tar.gz&license_key=<MY_LICENSE_KEY>`
2. `gunzip -f GeoIP2-City.mmdb.gz (this produced the file GeoIP2-City.mmdb)`

The Database reader gets built with no errors:
```
object DB {
  val dbFile = new File("db/GeoIP2-City.mmdb")
  val dbReader = new DatabaseReader.Builder(dbFile).build
}
```

The error happens when calling the .city() method like:
```
DB.dbReader.city(InetAddress.getByName("128.101.101.101"))
```

**Comment by oschwald** [comment]
It looks like you are downloading a `tar.gz` file but not untarring it. If you visit [www.maxmind.com](https://www.maxmind.com/) and use the chat feature there or email [support@maxmind.com](mailto:support@maxmind.com), they can provide more integration support.
