### ISSUE TITLE
GeoLite2-City.mmdb FileNotFound when running under Tomcat Parallel Deployment

### ISSUE THREAD

**Issue by erd2119** [maxmind/GeoIP2-java#121]
Hello,

We have been using the geoip2 (v 2.8.0) for a year or two in our Java application running on Tomcat 8.5.8 / JDK 8.0.111 and it has been working very well for us. Thank you.

Recently we tried to deploy our applications using Tomcat's Parallel Deployment feature (which is very simple and explained below) and we are now receiving a GeoLite2-City.mmdb FileNotFound error. It is very clear what is happening, let me explain. We typically deploy our application as ROOT.war within Tomcat. Tomcat's Parallel Deployment, works by convention where you simply add a version to the ROOT.war file name. So instead of ROOT.war you deploy a file named ROOT##001.war and then when you deploy the next version of your application it is ROOT##002.war and so on. Existing sessions will run against ROOT##001 and new sessions against ROOT##002 and at some point you can get rid of ROOT##001.

The error we are getting from the maxmind code, is pretty self explanatory. It seems you are urlencoding the ROOT.war filename so the ## is being translated to %23%23, so the code is looking for the file under a directory named /ROOT%23%230001/WEB-INF/classes/ when it should be looking for the file under a directory named/ROOT##0001/WEB-INF/classes/. See the stacktrace below.

[dispatcherServlet] in context with path [##0001] threw exception
java.io.FileNotFoundException: /usr/local/apache-tomcat-8.5.31/webapps-pwr/ROOT%23%230001/WEB-INF/classes/GeoLite2-City.mmdb (No such file or directory)
at java.io.RandomAccessFile.open0(Native Method)
at java.io.RandomAccessFile.open(RandomAccessFile.java:316)
at java.io.RandomAccessFile.<init>(RandomAccessFile.java:243)
at com.maxmind.db.BufferHolder.<init>(BufferHolder.java:19)
at com.maxmind.db.Reader.<init>(Reader.java:116)
at com.maxmind.geoip2.DatabaseReader.<init>(DatabaseReader.java:35)
at com.maxmind.geoip2.DatabaseReader.<init>(DatabaseReader.java:23)
at com.maxmind.geoip2.DatabaseReader$Builder.build(DatabaseReader.java:129)  

Note for reference: 

https://tomcat.apache.org/tomcat-8.5-doc/config/context.html#Parallel_deployment

**Comment by oschwald** [comment]
We just take a `File` and we pass untouched to the constructor for `RandomAccessFile`. I don't see how this could be a bug in this library.

**Comment by erd2119** [comment]
Can you point me to the relevant lines of code in the source so we can investigate further on our side?

**Comment by oschwald** [comment]
It is in the stack trace, [line 19 of `com.maxmind.db.BufferHolder`](https://github.com/maxmind/MaxMind-DB-Reader-java/blob/master/src/main/java/com/maxmind/db/BufferHolder.java#L19).

**Comment by erd2119** [comment]
RESOLVED.

We initialize our GeoLite2-City.mmdb db using an ApplicationListener at application initiation. The initial code we used to do this was:

File database = new File(classLoader.getResource("GeoLite2-City.mmdb").getFile());

As mentioned in the initial bug report the file path was being URL encoded, converting ## to %23%23 resulting in a fileNotFound exception. URL decoding fixed this issue. The fix:

File database = new File(URLDecoder.decode(classLoader.getResource("GeoLite2-City.mmdb").getFile(),"UTF-8"));
