### ISSUE TITLE
SSLPeerUnverifiedException: peer not authenticated

### ISSUE THREAD

**Issue by jflebeau** [maxmind/GeoIP2-java#126]
Running with OpenJDK 11 (Ubuntu 18.04) and `HttpClient` 4.5.8, I'm getting intermittent `SSLPeerUnverifiedException: peer not authenticated` errors, any suggestions?

**Comment by oschwald** [comment]
Are you still experiencing this? I would suggest following up with [support@maxmind.com](mailto:support@maxmind.com). I don't think the issue is particular to this library.
