### ISSUE TITLE
remediate CWE-209 vulnerability in geoip2 2.9.0

### ISSUE THREAD

**Issue by dian-xh** [maxmind/GeoIP2-java#138]
greetings,
during recent vulnerability scan in our project, the geoip2 jar was fond to have the CWE-209 vulnerability. More technical details:

- https://cwe.mitre.org/data/definitions/209.html
- api: java.lang.Thread.getStackTrace():StackTraceElement[]
- caller: com.maxmind.geoip2.DatabaseReader.get(InetAddress;Class;String):Object at line  144

this issues affects software using this library and might remediation. thanks!

**Comment by oschwald** [comment]
The code referred to adds the method called to the exception message. The exception message is intended for the developer developing the application. I don't know if CWE-209 is relevant here.

**Comment by oschwald** [comment]
I am closing this for the above reason.
