### ISSUE TITLE
Remove final keyword from classes

### ISSUE THREAD

**Issue by LukeButters** [maxmind/GeoIP2-java#141]
Please remove the final keyword from like classes such as City and  CityResponse so they can be mocked.

**Comment by oschwald** [comment]
I'd prefer to not make inheritance part of the support API surface. Is there a reason why you need to mock these given that they are, for the most part, data classes? Can't you just use the actual class with the test data?

**Comment by LukeButters** [comment]
I can't remember exactly why i want it so much. Your correct I can use that class the pain is that constructor is pretty long so the test code I think doesn't look so nice and it is not super easy to work with.

**Comment by oschwald** [comment]
As mentioned above, we would prefer not to have to support inheritance as part of the API going forward. We are open to other ideas that may reduce friction when mocking data for tests though.
