### ISSUE TITLE
 Why Taiwan, Hong Kong, and Macau do not belong to China？

### ISSUE THREAD

**Issue by Gubaidan** [maxmind/GeoIP2-java#165]
"country":"香港",  "ip":"203.198.135.33" 
it is correct?

**Comment by oschwald** [comment]
We get our date from [GeoNames](https://www.geonames.org/) and use [ISO 3166-1](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) for countries. Hong Kong is assigned the country code [HK](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#HK) there.

Somewhat confusingly, Hong Kong is also a [subdivision of CN under ISO 3166-2](https://en.wikipedia.org/wiki/ISO_3166-2:HK).
