### ISSUE TITLE
Availability of ASN

### ISSUE THREAD

**Issue by titpetric** [maxmind/GeoIP2-java#179]
Reading the code for getAutonomousSystemNumber(), the comment says:

~~~java
/**
  * @return The <a
  * href="http://en.wikipedia.org/wiki/Autonomous_system_(Internet)"
  * >autonomous system number</a> associated with the IP address.
  * This attribute is only available from the City and Insights web
  * service end points and the GeoIP2 Enterprise database.
  */
~~~

Firstly, there's GeoLite2-ASN available which is supposed to have it.

Secondly, the databaseType for Enterprise doesn't enable DatabaseType.ASN ([source](https://github.com/maxmind/GeoIP2-java/blob/master/src/main/java/com/maxmind/geoip2/DatabaseReader.java#L135)).

~~~java
        if (databaseType.contains("GeoLite2-ASN")) {
            type |= DatabaseType.ASN.type;
        }
...
        if (databaseType.contains("Enterprise")) {
            type |= DatabaseType.ENTERPRISE.type | DatabaseType.CITY.type | DatabaseType.COUNTRY.type;
        }
~~~

I suspect DatabaseType.ASN.type should be enabled here, correct?

**Comment by titpetric** [comment]
Upon further reading it seems the ASN API is omitted from the Enterprise DB, but it is available over traits. What's the availability of ASN data over traits with other database types?

**Comment by oschwald** [comment]
The Enterprise database includes the ASN data in the traits object. If you are using the ASN database, please follow the [example in the README.md](https://github.com/maxmind/GeoIP2-java#asn).

**Comment by titpetric** [comment]
The EnterpriseResult API implements city and country endpoints, with the
same api as CityResult and CountryResult; similarly it could implement
AsnResult for consistency, or, to be more aggressive: it should not exist
as it’s a superset of all available results (i assume).

I suggest that the API could be made consistent with Asn, or outright
removed as it’s a superset of all existing APIs. CountryResult should work
with a city database or an enterprise one, it’s my understanding that it
already does? Same should be true for Asn.

I’m assuming the APIs exist bundled together as supersets due to fetching a
wider dataset at once (asuming country+city are a single record for the
city mmdb). There’s a level of indirection here where there is an
opportunity to provide a consistent API regardless of database type
(EnterpriseResult as the API for any underlying database). It would be
expected that getCity() would return null (or even an Optional!) with a
country mmdb, etc.
