### ISSUE TITLE
See if the attribute is set

### ISSUE THREAD

**Issue by qqilihq** [maxmind/GeoIP2-java#215]
[Here](https://github.com/maxmind/GeoIP2-java#what-data-is-returned), the documentation says:

> Every record class attribute has a corresponding predicate method so you can check to see if the attribute is set.

However I cannot find this, or I am probably entirely misunderstanding it. Is there some more documentation available for this?

**Comment by oschwald** [comment]
Thanks, that is in fact wrong. I'll remove it.

All of the record classes returned by the response model classes, e.g., `com.maxmind.geoip2.record.Country` will be non-null. An empty object will be returned if necessary. The end values, eg., the country code, may be null if they are not part of the response.

**Comment by oschwald** [comment]
This sentence was removed in 2439856.

**Comment by qqilihq** [comment]
Thanks for the clarification!

One follow-up though: 

For the boolean information which is contained e.g. in the `Traits` I get `false`, even if the information is not given (so I cannot determine easily, wether it’s really `false`, or just not provided). Any way to distinguish these cases?

**Comment by oschwald** [comment]
For both the database and web services, the key is not included if the value is false. All of the boolean GeoIP2 values should be regarded as false if they are not true.
