### ISSUE TITLE
Documentation: Does the client support updategeodb?

### ISSUE THREAD

**Issue by Fjolnir-Dvorak** [maxmind/GeoIP2-java#235]
Does the client has any problems if I update the geo-database via updategeodb and if yes are there any possibilities that I will get exceptions in the time the database is rewritten by updategeodb? I am not sure whether I need to time the update to deconstruct the geodatabase-cliente at first, update the geodb, wait until it is finished and reconstruct the client, or if I can ignore this whole issue and the client is able to handle an underlying file change.

**Comment by oschwald** [comment]
When you say `updategeodb`, do you mean `geoipupdate`? If you are on Linux or a POSIX system, then it is safe to use `geoipupdate` while this client has a database open. The file is replaced atomically and the client will continue to use the old version. If you are on Windows or a system that does not support atomically replacing a file, then you may run into issues.
