### ISSUE TITLE
Java library crashes on presence of location fields: average_income and population_density

### ISSUE THREAD

**Issue by nielsbasjes** [maxmind/GeoIP2-java#250]
I have a project that uses this library and in order to have stable unit tests I have copied a small part of the https://github.com/maxmind/MaxMind-DB/ project and generate my own (immutable and predictable) mmdb files. https://github.com/nielsbasjes/logparser/tree/master/GeoIP2-TestData

Simply put: I have manually created test json files (with mostly fake data) which have been converted into mmdb files that I use for my tests. In those tests I simply define many fields that are defined in the file format.

After updating to version 2.15.0 my tests crashed with a `java.lang.IllegalArgumentException: argument type mismatch`

I traced this to the point where the mmdb loading classes (`Decoder`) try to create an instance of Location where it fails because of the list of available constructor arguments is different from the types of the provided parameters.

[The constructor is defined as this](https://github.com/maxmind/GeoIP2-java/blob/main/src/main/java/com/maxmind/geoip2/record/Location.java#L26)
```
    @MaxMindDbConstructor
    public Location(
            @JsonProperty("accuracy_radius") @MaxMindDbParameter(name="accuracy_radius") Integer accuracyRadius,
            @JsonProperty("average_income") @MaxMindDbParameter(name="average_income") Integer averageIncome,
            @JsonProperty("latitude") @MaxMindDbParameter(name="latitude") Double latitude,
            @JsonProperty("longitude") @MaxMindDbParameter(name="longitude") Double longitude,
            @JsonProperty("metro_code") @MaxMindDbParameter(name="metro_code") Integer metroCode,
            @JsonProperty("population_density") @MaxMindDbParameter(name="population_density") Integer populationDensity,
            @JsonProperty("time_zone") @MaxMindDbParameter(name="time_zone") String timeZone
    ) {
```

Yet the parameters with which is is called (copied from my debugger):
```
parameters = {Object[7]@1506} 
 0 = {Integer@1510} 14
 1 = {Long@1511} 16
 2 = {Double@1512} 52.5
 3 = {Double@1513} 5.75
 4 = {Integer@1514} 15
 5 = {Long@1515} 17
 6 = "Europe/Amsterdam"
```

Apparently there is a mismatch between the types for "average_income" and "population_density".
[The source for these fields in my application look like this:](https://github.com/nielsbasjes/logparser/blob/master/GeoIP2-TestData/source-data/GeoIP2-City-Test.json#L134)
```
      "location": {
        "accuracy_radius": 14,
        "latitude": "52.5",
        "longitude": "5.75",
        "time_zone": "Europe/Amsterdam",
        "metro_code": "15",
        "average_income": 16,
        "population_density": 17
      },
```

Looking at the mmdb definition I find these definitions in the tool used to create the test files:
https://github.com/maxmind/MaxMind-DB/blob/main/test-data/write-test-data.pl#L456

        accuracy_radius                => 'uint16',
        latitude                       => 'double',
        longitude                      => 'double',
        time_zone                      => 'utf8_string',
        metro_code                     => 'uint16',
        average_income                 => 'uint32',
        population_density             => 'uint32',

Looking at this it seems clear that a `uint16` is mapped to an `Integer` and a `uint32` is mapped to a `Long`.
If I simply remove those two fields from my input json and regenerate the mmdb files the loading of these files no longer crashes.

I also found that in the https://github.com/maxmind/MaxMind-DB project none of the test files contain these two fields.

I'm not sure if this is a bug in the Java library, in the tool that writes the test files or perhaps in the specification.

**Comment by oschwald** [comment]
If I am understanding this issue correctly, this is similar to #178. However, in this case, I am less inclined to consider it a bug as these values will never exceed 2^31. `maxmind-db` is able to decode a `uint32` to an `Integer` as long as it doesn't exceed the maximum value of an `Integer`.

**Comment by oschwald** [comment]
Actually, I apologize. I think I was confusing the Java database reader with another language where we do support this decode.

That said, I don't believe we have a public database with these two fields. They are only available for the web service.

**Comment by nielsbasjes** [comment]
I implemented these testing files (with dummy values for those two fields) so I have reproducible values for each of the possible getters I found in the Java library.
My interpretation of your feedback here is that having these two values in the Java library is effectively useless because these fields will never be filled.

Why are these in the Java API then?
You cannot be using this API internally because then you would have had this crash also.

**Comment by oschwald** [comment]
These fields are provided by our web service that use the same model classes. I agree that it is misleading that they are marked as `MaxMindDbParameter`. They are only intended to be used when deserializing from JSON.

**Comment by nielsbasjes** [comment]
Ok, thanks for the fast feedback.
I understand these fields will never be available in production mmdb files.

Since my code should only work with locally available database files I'm going to simply remove these fields in my project.

In general I currently see the solution I have employed as one of the few (the only?) valid solutions to test an application that uses your library offline.
For this testing application I still think that the problem I ran into matters.
Apparently the average_income and population_density are defined in both the fileformat and the Java API, yet they are no longer compatible (since 2.15)

**Comment by oschwald** [comment]
The file format allows arbitrary data. Those fields are used in the separate internal-only `GeoIP2-DensityIncome` database and they are not part of the `traits` map there.

Given the nature of the changes in 2.15 generally, it probably should have had a major version bump. However, I don't know if anyone would have reasonably anticipated that someone would be using test databases with fields that have never appeared in an actual database.

**Comment by nielsbasjes** [comment]
Note that those fields are defined in the tool to write the test files.
Perhaps the solution is to remove them from there?

**Comment by oschwald** [comment]
They are defined in that tool for the `GeoIP2-DensityIncome` test database that is available in that repo.

**Comment by nielsbasjes** [comment]
For my application I have been able to solve the problem I ran into by simply dropping these fields because they will never be available anyway.

Yet I still see that you have a set of test files with fields that would crash the Java API.
Since you say these are internal only I leave it up to you to choose either to close this with "Won't fix" or to change the generated test files and/or the Java API.

Thanks for the quick feedback. It really helped.

**Comment by oschwald** [comment]
What test files are you referring to? If you mean the `GeoIP2-DensityIncome` database, that database does not work with this module at all as there are no models for it. You would receive [this exception](https://github.com/maxmind/GeoIP2-java/blob/42cc0ac02b6936b21ca8d5249248180ebc0875da/src/main/java/com/maxmind/geoip2/DatabaseReader.java#L133) immediately upon opening it. Grepping the `MaxMind-DB` repo, that is the only database with those fields. The model in question is only used for GeoIP2 City, Country, and Enterprise.
