### ISSUE TITLE
DatabaseReader doesn't correctly close

### ISSUE THREAD

**Issue by danielkaneider** [maxmind/GeoIP2-java#26]
Hi, 

it looks like the DatabaseReader.close() of geoip2-2.0.0 doesn't work as excpeted. Looking deeper it seems that just an AtomaticReference is set to null. The problem is that, closing the reader, moving the db file, and opening it again, fails. This is demonstrated in the JUnit test case below. Moreover a System.gc should not be necessary.

```
import java.io.File;
import java.io.IOException;
import java.net.InetAddress;
import java.net.UnknownHostException;

import org.junit.Assert;
import org.junit.Test;

import com.maxmind.db.Reader.FileMode;
import com.maxmind.geoip2.DatabaseReader;
import com.maxmind.geoip2.exception.GeoIp2Exception;

public class TestDatabaseReaderClose {
    @Test
    public void test1() throws Exception {
        executeTest(false, true);
    }
    @Test
    public void test2() throws Exception {
        executeTest(true, false);
    }
    @Test
    public void test3() throws Exception {
        executeTest(false, true);
    }
    @Test
    public void test4() throws Exception {
        executeTest(true, false);
    }
    private void executeTest(boolean memoryMapped, boolean gc) throws IOException, GeoIp2Exception, UnknownHostException {
        String fileName = "C:\\Data\\GeoIP2-City.mmdb";

        File file1 = new File(fileName);
        File file2 = new File(fileName + ".temp");

        DatabaseReader reader1 = new DatabaseReader.Builder(file1).fileMode(memoryMapped ? FileMode.MEMORY_MAPPED : FileMode.MEMORY).build();
        Assert.assertEquals("GB", reader1.city(InetAddress.getByName("80.1.1.1")).getCountry().getIsoCode());
        reader1.close();
        if (gc)
            System.gc();

        Assert.assertTrue(file1.renameTo(file2));
        Assert.assertTrue(file2.renameTo(file1));

        DatabaseReader reader2 = new DatabaseReader.Builder(file1).build();
        Assert.assertEquals("GB", reader2.city(InetAddress.getByName("80.1.1.1")).getCountry().getIsoCode());
        reader2.close();
    }
}

```

**Comment by heruan** [comment]
What is the status of this? I'm experiencing Out Of Memory issues when deploying on WildFly an application using GeoIP2: on undeploying I call `close()`, but after a couple of redeploying it goes OOM nevertheless.

**Comment by oschwald** [comment]
@heruan, to confirm, you are using this in memory map mode? Does it happen when you use memory mode? https://github.com/maxmind/MaxMind-DB-Reader-java/pull/14/files might help, but it used undocumented calls and likely won't work in all environments.

**Comment by heruan** [comment]
I'm using the default mode ATM. I'll try `MEMORY` mode and let you know!

**Comment by heruan** [comment]
No luck with `MEMORY` mode, still getting this after redeploy:

```
java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3744)
	at java.io.ByteArrayOutputStream.toByteArray(ByteArrayOutputStream.java:192)
	at com.maxmind.db.BufferHolder.<init>(BufferHolder.java:66)
	at com.maxmind.db.Reader.<init>(Reader.java:89)
	at com.maxmind.geoip2.DatabaseReader.<init>(DatabaseReader.java:64)
	at com.maxmind.geoip2.DatabaseReader.<init>(DatabaseReader.java:54)
	at com.maxmind.geoip2.DatabaseReader$Builder.build(DatabaseReader.java:160)
    ...
```

like calling `close()` didn't free memory.

**Comment by oschwald** [comment]
I don't think the issue you are experiencing isn't related to the memory mapping issue discussed above. Are you holding on to the old GeoIP2 Reader objects? When using the memory mode, the file is in an array-backed `ByteBuffer` that should be garbage collected like any other object in Java.

**Comment by hc-codersatlas** [comment]
@oschwald it gets garbage collected if there are no references to it. Calling close doesn't necessarily release the references. In the code, `BufferHolder` holds a copy of this `ByteBuffer`. Is the reference to it released properly?

**Comment by hc-codersatlas** [comment]
@oschwald the reference to the buffer holder is closed - not all references to the ByteBuffer itself. Main difference. The ByteBuffer would then still be lingering.

**Comment by ryc8889** [comment]
why was the `close()` implementation in `Reader` switched back to just set the bytebuffer to null instead of setting it to null and closing it such as what the original MR intended in https://github.com/maxmind/MaxMind-DB-Reader-java/pull/8

looking at the history for the reader file, it seems it was reverted back to just setting the `AtomicReference` to null in this commit. https://github.com/maxmind/MaxMind-DB-Reader-java/commit/51f5b5c1a6ece5e529a0006a1bc64a81d9c6ef75#diff-ff6397fc2348ea80897a61f94b8fe80c

I'm currently having an issue updating database file and having the reader successfully query the updated file. I keep getting MaxMind DB has been closed exceptions. The metadata is being properly read in from the updated .mmdb file but actual queries lead to a `ClosedDatabaseException`. I'm using a `Reader` object directly instead of a `DatabaseReader`  so apologies if this should have gone under the Reader repo instead of this one

**Comment by oschwald** [comment]
Because as of #7, there was nothing left to close on the `BufferHolder`.

As for your particular issue, it sounds like  you are continuing to use the old reader after it has been replaced. It is hard to say why without seeing your code.

**Comment by ryc8889** [comment]
I'm holding the `Reader` in an `AtomicReference` and I do a getAndSet with a newly constructed reader in my reload method.  The newly constructed reader prints out the correct metadata from the updated .mmdb file but for some reason the `BufferHolder` returns null in `Reader.getBufferHolder()`.

I'm testing this locally on a macbook pro macOS 10.13.5. Right now running into this problem through a unit test but i've also had problems when deploying to my dev environment (Centos 7)

**Comment by oschwald** [comment]
Even if you have the reader in an atomic reference, the lookup on the reader is not atomic. If you close the reader in another thread before the lookup is complete, you will get a `ClosedDatabaseException`.

**Comment by ryc8889** [comment]
also the pull request you referenced in your last post - https://github.com/maxmind/GeoIP2-java/pull/7 references using the functionality in this commit https://github.com/maxmind/MaxMind-DB-Reader-java/commit/63cb7181 but that functionality was overwritten as you can see by the current src code the `Reader` constructor that uses an InputStream no longer uses a `ThreadBuffer`. Was that due to the introduction of the `BufferHolder`?

**Comment by oschwald** [comment]
@ryc8889, I am not sure what you are asking. We still have a constructor that takes an `InputStream`, which is the fundamental feature introduced by the commit that you referenced. As of https://github.com/maxmind/MaxMind-DB-Reader-java/pull/5/commits/30b66e569b1d0d2edd828872c0b50b17efe5b17a, we no longer use a `ThreadLocal` as its use caused a resource leak.

I don't think this discussion is related to the original bug report, which, I believe, is referring to the fact that Java does not allow you to explicitly close memory mapped files (at least without doing questionable things like https://github.com/maxmind/MaxMind-DB-Reader-java/pull/5/commits/30b66e569b1d0d2edd828872c0b50b17efe5b17a).

**Comment by oschwald** [comment]
I am closing this issue as this is the wrong repo and it has wandered quite far from the original report, which we cannot reasonably fix anyway.
