### ISSUE TITLE
Throwing AddressNotFoundException when IP address cannot be resolved is expensive

### ISSUE THREAD

**Issue by DigitalGoldfish** [maxmind/GeoIP2-java#28]
From a performance point of view it would be much better to just return null in this case. The overhead that is required to generate the exception object is noticeable when profiling our application.

**Comment by beamerblvd** [comment]
I understand the issue of private IPs, but I agree with Greg that it's still an integration issue. You shouldn't be doing a location lookup for internal/loopback/link-local/net-local/etc. addresses. Only for publicly-allocatable addresses. I would recommend checking an IP address for public allocatability before looking it up in the database. There are several OSS libraries available to help you do that. It's what we do before looking it up in the database.

**Comment by phraktle** [comment]
I would also vote +1 on not using an Exception for the purposes of a not found item in general. But indeed this is a very low percentage (fraction of a percent) in practice, so it's acceptable in this context. In Java 8, using Optional would be idiomatic here.

**Comment by phraktle** [comment]
Btw, the JVM automatically optimizes out populating the stack trace if an exception keeps getting thrown in a hot code path (see -XX:-OmitStackTraceInFastThrow). So even it happens too much, it should stop being a problem :)

**Comment by phraktle** [comment]
@DigitalGoldfish, in our app, we apply this filter prior to trying to look up the GeoIP:

```
InetAddress ip;
...
ip.isLoopbackAddress() ||
ip.isAnyLocalAddress() ||
ip.isLinkLocalAddress() ||
ip.isSiteLocalAddress()
```

This might help you cut down on these exceptions.

**Comment by DigitalGoldfish** [comment]
@phraktie Thanks! I think we put something like that in place to deal with the performance issues we've seen. It seemed to be sufficient as I had no further complaints from the ops team.

**Comment by LukeButters** [comment]
Could we re-open this and add either methods which return Optional or methods which return null (e.g. `getOrNull` which do not throw exceptions when the value is null.

* Throwing exceptions to control code flow is not good coding practice.
* Those exceptions are expensive and the JVM can't be relied upon to make that go away.
* Trying to remove internal/loopback etc IP addresses is not a good solution as the doco does not have a guarantee that every other IP address is in the data base.

**Comment by LukeButters** [comment]
Neat it is in, thanks!
Do you have a schedule for when this change would be available on maven central?

**Comment by oschwald** [comment]
@LukeButters, thanks for the PR! There are several other changes we would like to get in for this release. Given the time of the year, I am guessing the release won't happen until after Black Friday/Cyber Monday.
