### ISSUE TITLE
Add equals and hashCode to the classes

### ISSUE THREAD

**Issue by satsen** [maxmind/GeoIP2-java#309]
I created a map with Country as key but because equals and hashCode are not implemented, the same country gets treated as different keys.

**Comment by satsen** [comment]
Well I was using this class because it included the country names but I just switched to using the ISO 2-letter country code and using the Java Locale class to get country names.

**Comment by oschwald** [comment]
Sorry for not responding to this before. It is mostly an issue of maintenance that makes me leary of providing these on all the model classes. I suspect once we drop support for older Java versions, we may switch to using records for these and get `equals` and `hashCode` for free.

**Comment by satsen** [comment]
@oschwald It's alright. I was using the class in the wrong way anyways. Records in the future (no matter how far that is) will be cool, even though it will not affect me as I directly take the ISO code from Country object.
