### ISSUE TITLE
JPMS support

### ISSUE THREAD

**Issue by robertvazan** [maxmind/GeoIP2-java#310]
Please make this library an [automatic module](https://stackoverflow.com/questions/46741907/what-is-an-automatic-module) or even better use [moditect](https://github.com/moditect/moditect) to generate multi-release JAR with module-info.java. This will make the library easier to use in dependent apps and libraries that make use of [JPMS](https://en.wikipedia.org/wiki/Java_Platform_Module_System) introduced in Java 9.

**Comment by oschwald** [comment]
I agree. This seems like something we should add.

**Comment by oschwald** [comment]
As of 4.0.0, this library is now a module.
