### ISSUE TITLE
Version 4.0.0 and 4.0.1 cannot access com.maxmind.db.CHMCache

### ISSUE THREAD

**Issue by bensonhon** [maxmind/GeoIP2-java#343]
I have a compile failure when switching to 4.0.0 and 4.0.1:

[ERROR]   bad class file: /Users/benson.hon/.m2/repository/com/maxmind/db/maxmind-db/3.0.0/maxmind-db-3.0.0.jar(com/maxmind/db/CHMCache.class)
[ERROR]     class file has wrong version 55.0, should be 52.0
[ERROR]     Please remove or make sure it appears in the correct subdirectory of the classpath.

How should I resolve it?

**Comment by bensonhon** [comment]
Looks like it is using java 9, probably that's why coz I'm still using java 8 at the moment. Will test it and post here.

**Comment by oschwald** [comment]
The last version to support Java 8 was 2.16.1. Java 11 is currently required.
