### ISSUE TITLE
GraalVM Support

### ISSUE THREAD

**Issue by kthumin** [maxmind/GeoIP2-java#348]
Does maxmind currently support GraalVM? I am having below error with GraalVM. 

Im using geoip2 with Spring Boot 3.1 and GraalVM. 
```
Caused by: com.maxmind.db.ConstructorNotFoundException: No constructor on class com.maxmind.db.Metadata with the MaxMindDbConstructor annotation was found.
```

**Comment by oschwald** [comment]
I haven't used GraalVM, but it appears that you will need to configure it to support reflection for both the `geoip2` and `maxmind-db` dependencies.

**Comment by kthumin** [comment]
Would you be so kind to provide the list of classes that are needed to be configured for reflection?  For now, configuring all classes for reflection works.

**Comment by oschwald** [comment]
In addition to the `Metadata` class above, reflection is used on `com.maxmind.geoip2.model.*` and `com.maxmind.geoip2.record.*`.
