### ISSUE TITLE
Wrong comment about locales

### ISSUE THREAD

**Issue by Fedessi8187** [maxmind/GeoIP2-java#357]
Hello,

In the file `AbstractNamedRecord.java` from the `com.maxmind.geoip2.record`, the `getName()` method is commented as follow:
```
    /**
     * @return The name of the city based on the locales list passed to the
     * {@link com.maxmind.geoip2.WebServiceClient} constructor. This
     * attribute is returned by all end points.
     */
```

It seems technically false as the `locales` can be passed to any provider, or set by default.

I then suggest the following comment:
```
/**
     * @return The name of the city based on the locales list passed to the
     * provider constructor. This attribute is returned by all end points.
     */
```

**Comment by oschwald** [comment]
Thanks! Yeah, there are a number of instances like this as the models were used for the web services before database support was added.
