### ISSUE TITLE
GeoIp2Provider doesn't define insights methods

### ISSUE THREAD

**Issue by echrisinger** [maxmind/GeoIP2-java#359]
Love that you guys package a great client lib. Thanks for the hard work.

One thing that would be useful would be including the insights methods on GeoIp2Provider, or another interface; this makes providing a test double for insights much more easily, as you don't have to wrap WebServiceClient to return a predictable response. We prefer to do this to avoid introducing the complexity of mocking frameworks.

Thanks!
Evan

**Comment by oschwald** [comment]
`GeoIp2Provider` provider is implemented by bothe the database reader and web service client. The former doesn't have an equivalent to Insights. However, it would make sense to add a `WebServiceProvider` given that we already have `DatabaseProvider` for the database reader.
