### ISSUE TITLE
where do i store the pom.xml file ?

### ISSUE THREAD

**Issue by KedemBarak** [maxmind/GeoIP2-java#38]
you are saying to use  and create pom.xml file
where do i store it ?

    <dependency>
        <groupId>com.maxmind.geoip2</groupId>
        <artifactId>geoip2</artifactId>
        <version>2.2.0</version>
    </dependency>

**Comment by oschwald** [comment]
You store it in the top-level directory of your repo. You can use any dependency manager that supports Maven artifacts.
