### ISSUE TITLE
Error when creating databse reader

### ISSUE THREAD

**Issue by jzapantis** [maxmind/GeoIP2-java#44]
I am new to GeoIP and am trying to set up a test app to try it out on the free databases. I have imported the DatabaseReader class as well as the DatabaseReader.Builder class, and when I create a DatabaseReader object the I get an error that says:

Exception in thread "main" java.lang.NoClassDefFoundError: com/maxmind/db/Reader$FileMode
	at com.maxmind.geoip2.DatabaseReader$Builder.<init>(DatabaseReader.java:76)
	at GeoIP.main(GeoIP.java:55)
Caused by: java.lang.ClassNotFoundException: com.maxmind.db.Reader$FileMode
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 2 more
Java Result: 1

I am not sure why this is, I have a File object pointing to my database and have no errors there. And I have properly added the GeoIP2.jar file to my project. Has anyone seen this error before?

![untitled](https://cloud.githubusercontent.com/assets/13191898/8514312/6a3fdc9c-235a-11e5-9479-709898b4144c.png)

**Comment by 2shortplanks** [comment]
Have you imported the underlying [DB reader classes](https://github.com/maxmind/MaxMind-DB-Reader-java)?

**Comment by jzapantis** [comment]
I am not sure which you are referring too, however here is a screen shot of my imports
![untitled](https://cloud.githubusercontent.com/assets/13191898/8534841/5276b5c2-240e-11e5-8a0a-03aa2ce0835d.png)

**Comment by jzapantis** [comment]
I have imported both DatabaseReader and DatabaseReader.Builder classes. Are those what you are referring to?

**Comment by oschwald** [comment]
If you are not using Maven-compatible dependency management, please add all the jar files from the geoip2-*-with-dependencies.zip file on the releases page to your class path.

**Comment by andyjack** [comment]
If you do want to use Maven dependencies, NetBeans makes it straightforward - once you add geoip2 as a dependency, building the project will pull in everything else that is needed.  http://wiki.netbeans.org/QuickStartJavaMavenProject

**Comment by oschwald** [comment]
I am going to close this. We updated the documentation to make it more clear how to use the JAR files directly without Maven or a compatible tool.
