### ISSUE TITLE
Class not found:

### ISSUE THREAD

**Issue by puppetMaster3** [maxmind/GeoIP2-java#49]
import com.maxmind.db.Metadata;
import com.maxmind.db.Reader;
import com.maxmind.db.Reader.FileMode;

It can't find these files. 
So it can't run - class not found.

**Comment by oschwald** [comment]
You need the MaxMind DB reader as well as several other dependencies. Please follow the [JAR installation instructions](https://github.com/maxmind/GeoIP2-java#jar-files) if you are not using a Maven-compatible build tool.
