### ISSUE TITLE
Region missing

### ISSUE THREAD

**Issue by Proximator** [maxmind/GeoIP2-java#60]
Hi, I was using the old legacy library and it had the region codes and names hard coded in.

Is there any plan to add them back?
Why were they added as a class instead of in the database itself?

Regards

**Comment by oschwald** [comment]
I am not sure I follow the question. There is no plan to hard code the regions into GeoIP2. This was a misfeature of the legacy API. In GeoIP2, the subdivisions are stored in the database.

**Comment by Proximator** [comment]
But I was using regionName.regionNameByCode(countryCode, regionCode) to get the region name.
How can I do the same thing with the new API ?
I mean get region code and region name from an IP address

**Comment by oschwald** [comment]
Please see our [City example](https://github.com/maxmind/GeoIP2-java#city) for one way to get the subdivision name.

**Comment by Proximator** [comment]
But this create a regression in my code, because for a given IP address, the legacy library used to give me : "London, City of" as region while now, it is giving me "England"

Does this mean that the region available at : https://github.com/maxmind/geoip-api-java/blob/master/src/main/java/com/maxmind/geoip/regionName.java
Does not exist anymore ?

**Comment by oschwald** [comment]
Correct. The hard coded region names do not exist.

**Comment by Proximator** [comment]
We are using this class in our code, what can we do to upgrade to GeoIP2 ?

**Comment by oschwald** [comment]
If you are a paying customer, I'd suggest contacting [support@maxmind.com](mailto:support@maxmind.com) or using our online chat for support.
