### ISSUE TITLE
Using legacy databases with the Java API?

### ISSUE THREAD

**Issue by mmoayyed** [maxmind/GeoIP2-java#61]
I had a look at:
http://dev.maxmind.com/geoip/legacy/geolite/

> The GeoLite databases are our free IP geolocation databases. They are updated on the first Tuesday of each month. These databases are offered in the same binary and csv formats as our subscription databases. Any code which can read the subscription databases can also read the GeoLite databases.

So I downloaded http://geolite.maxmind.com/download/geoip/database/GeoIPv6.dat.gz
and unzipped into a .dat file. 

Have the following code:

```
        File file = new File("C:\\GeoIPv61.dat");
        DatabaseReader reader = new DatabaseReader.Builder(file)
                .withCache(new CHMCache(100)).build();

        InetAddress ipAddress = InetAddress.getByName("128.101.101.101");
        CityResponse response = reader.city(ipAddress);
        Country country = response.getCountry();
        System.out.println(country.getIsoCode());
        System.out.println(country.getName());
        System.out.println(country.getNames().get("zh-CN"));
```

Result:

```
Exception in thread "main" com.maxmind.db.InvalidDatabaseException: Could not find a MaxMind DB metadata marker in this file (GeoIPv61.dat). Is this a valid MaxMind DB file?
```

How should one use the java api here to access the legacy databases?

**Comment by mmoayyed** [comment]
I suspect this should be used instead: http://dev.maxmind.com/geoip/geoip2/geolite2/ ?

**Comment by oschwald** [comment]
Yes, this API is for use with the GeoLite2/GeoIP2 databases. The [legacy API](https://github.com/maxmind/geoip-api-java) should be used with the legacy databases.
