### ISSUE TITLE
Is there any option exist for finding location from Longitude and Latitude?

### ISSUE THREAD

**Issue by naseefcse** [maxmind/GeoIP2-java#63]
I want to use GeoIP2 Java API for location detection. I found a way for detecting location from IP. But it is not a comprehensive way if user is behind of a proxy server. Is there any way exist for detecting location from Longitude and Latitude using GeoIP2 Java API? I want to avoid using Google API for detecting location as it is not fully free.

I am expecting a quick response or resolution regarding this.

Thanks.

**Comment by oschwald** [comment]
No, this is not possible. The locations are stored by IP address and you cannot look up by other fields. You might want to look at [GeoNames](http://www.geonames.org/) as a possible solution.
