### ISSUE TITLE
#2.6.0 com/maxmind/db/Decoder.java:272:in `decodeArray': java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.node.ArrayNode

### ISSUE THREAD

**Issue by ebuildy** [maxmind/GeoIP2-java#65]
With the version 2.6.0, downloaded at https://github.com/maxmind/GeoIP2-java/releases/download/v2.6.0/geoip2-2.6.0-with-dependencies.zip, I came across this issue:

> com/maxmind/db/Decoder.java:272:in `decodeArray': java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.node.ArrayNode.<init>(Lcom/fasterxml/jackson/databind/node/JsonNodeFactory;Ljava/util/List;)

When trying to instance a DatabaseReader, with jRuby (this is to build a logstash filter plugin):

````
db_file = JavaIO::File.new(@database)
@parser = DatabaseReader::Builder.new(db_file).build();
````

It looks like an issue with Jackson lib?

**Comment by oschwald** [comment]
It sounds like the wrong version of `jackson-databind` is being loaded. 2.7.0+ is required. Please make sure you are not loading another version.

**Comment by ebuildy** [comment]
Yes you are right, LogStash actually still uses https://github.com/guyboertje/jrjackson, I guess this is the reason, but I see the next version will use jackson 2.7.1 (https://github.com/elastic/logstash/blob/ad6cb41726b928f29f17ae08aa12f0e5b651120f/logstash-core-event-java/lib/logstash-core-event-java_jars.rb), so I can wait for this ;-)

Any chance to have built JARs for the 2.5.0 release? https://github.com/maxmind/GeoIP2-java/releases/tag/v2.5.0

Many thanks,

**Comment by oschwald** [comment]
I added the missing `geoip2-2.5.0-with-dependencies.zip` to that release.
