### ISSUE TITLE
New transport created unnecessarily for http requests

### ISSUE THREAD

**Issue by rocketraman** [maxmind/GeoIP2-java#70]
This line creates a new transport on each request:

https://github.com/maxmind/GeoIP2-java/blob/master/src/main/java/com/maxmind/geoip2/WebServiceClient.java#L281

As per the comment, this is done because the transport is not thread-safe. However, according to Google the transport *is* thread-safe:

"Implementation is thread-safe. For maximum efficiency, applications should use a single globally-shared instance of the HTTP transport."

From:

https://developers.google.com/api-client-library/java/google-http-java-client/reference/1.20.0/com/google/api/client/http/javanet/NetHttpTransport

**Comment by oschwald** [comment]
Thanks for point that out. We'd be happy to accept a PR to fix the issue, if you want to make one.

**Comment by rocketraman** [comment]
Sure, I can do that. I think with this change the `testTransport` can be removed and replaced with `transport` to allow the transport to be injectable, for both test and production code. Agreed?

**Comment by oschwald** [comment]
Yeah, that sounds reasonable. We'll want to leave the `testTransport` method in the builder though for compatibility, though it could be deprecated and replaced internally with a more general `transport` builder method.

**Comment by rocketraman** [comment]
> We'll want to leave the testTransport method in the builder though for compatibility, though it could be deprecated and replaced internally with a more general transport builder method.

Sounds good, see attached PR.
