### ISSUE TITLE
java.lang.ClassNotFoundException: com.maxmind.geoip2.DatabaseReader$Builder

### ISSUE THREAD

**Issue by mandalm** [maxmind/GeoIP2-java#74]
Hi am trying to write a UDF for pig and i have using this for getting ip details.

my code is ``` new DatabaseReader.Builder(db).build(); ```

which generate error stack like this.

```
Error: java.lang.ClassNotFoundException: com.maxmind.geoip2.DatabaseReader$Builder
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.XXXXXX.XXXXXXX.pig.ParseGeolocation.getDBReader(ParseGeolocation.java:86)
```

I am using maven for dependency.

Java version is 1.8

also if i trying to use ``` withcache() ```  then i always get com/maxmind/db/NodeCache not found. I have no idea why this happening.

Version I am using is ``` 2.7.0 ```

thanks and regards
Mithun Mandal

**Comment by oschwald** [comment]
It sounds like it isn't finding the jar file at runtime. Unfortunately, I am not that familiar with Pig. I'd suggest asking on StackOverflow.

**Comment by mandalm** [comment]
Sorry it was my mistake where maven not including jars while packaging.
