### ISSUE TITLE
JAR Conflict

### ISSUE THREAD

**Issue by umesh-mehta** [maxmind/GeoIP2-java#78]
Hi,
  In our project we are using older version of following jars and unfortunately we cannot replace with the jar which comes with maxmind geoip2-2.8.0 libs.
   **We are using**
     `commons-codec-1.7`
    ` jackson-annotations-2.4.2`
     `jackson-core-2.4.2`
    ` jackson-databind-2.4.2`
  
  **maxmind geoip2-2.8.0**
    `commons-codec-1.9`
    `jackson-annotations-2.8.0`
   ` jackson-core-2.8.2`
    `jackson-databind-2.8.2`

Due to this I am always below getting run time error 
```
java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.node.ArrayNode.<init>(Lcom/fasterxml/jackson/databind/node/JsonNodeFactory;Ljava/util/List;)V
	com.maxmind.db.Decoder.decodeArray(Decoder.java:272)
	com.maxmind.db.Decoder.decodeByType(Decoder.java:156)
	com.maxmind.db.Decoder.decode(Decoder.java:147)
	com.maxmind.db.Decoder.decodeMap(Decoder.java:281)
	com.maxmind.db.Decoder.decodeByType(Decoder.java:154)
	com.maxmind.db.Decoder.decode(Decoder.java:147)
	com.maxmind.db.Decoder.decode(Decoder.java:87)
	com.maxmind.db.Reader.<init>(Reader.java:132)
	com.maxmind.db.Reader.<init>(Reader.java:116)
	com.maxmind.geoip2.DatabaseReader.<init>(DatabaseReader.java:35)
	com.maxmind.geoip2.DatabaseReader.<init>(DatabaseReader.java:23)
	com.maxmind.geoip2.DatabaseReader$Builder.build(DatabaseReader.java:129)
```
Any suggestion ?
thanks in advance

**Comment by oschwald** [comment]
This API required `jackson-databind` 2.7 or greater. If you are not able to upgrade that dependency, you could try an older version of `geoip2`, e.g., 2.4 or 2.5.
