### ISSUE TITLE
Subdivions field is missing

### ISSUE THREAD

**Issue by pedromss** [maxmind/GeoIP2-java#81]
Hello, 

I'm using your API (v 2.5) through this library and requesting as: 

```scala
new WebServiceClient.Builder(userId, licenseKey).city(InetAddress.getByName(anIpAddress))
```

In the documentation I see the field [subdivisions](http://dev.maxmind.com/geoip/geoip2/web-services/#subdivisions) and I don't see any indication that it is optional.

Debugging I see that the `CityResponse` returned by this library has an empty `ArrayList` as the value for it's subdivisions field but when serialized into JSON the field isn't there which leads me to assume that when a collection is empty the key-value pair is not even serialized (in my opinion this is wrong, since an empty collection would also indicate that there are no subdivisions but wouldn't force the clients to check for the field's existence).

So, is the `subdivisions` field optional? Where does it say if it is or not?

**Comment by oschwald** [comment]
All of the response fields other than `/traits/ip_address` should be regarded as optional. The docs you link to also mention, "If a key maps to an undefined or empty value, it is not included in the JSON object. This applies both to top-level keys and the objects they map to."

**Comment by pedromss** [comment]
Yes I read that part of the documentation, however how am I supposed to know if a key will map to undefined or not? 

As a suggestion, the API should explicitly declare the fields to be optional or required which it doesn't, since there is a difference between an empty list and a non existing list. An empty list tells me no data was found for that key, a non existing list tells me something went wrong.

As a user of the API I propose that you serialize empty lists as `[]` instead of just not including them.

Thank you for the fast reply.
