### ISSUE TITLE
Wrong java version in documentation

### ISSUE THREAD

**Issue by kanedb** [maxmind/GeoIP2-java#83]
In GeoIP2-Java documentation (http://maxmind.github.io/GeoIP2-java/) the requirements states:
"MaxMind has tested this API with Java 6 and above."

But versions >= 2.8 cant run on Java 6.
It would be helpful if that page shows a version summary of GeoIP versions x Java supported versions.

**Comment by oschwald** [comment]
Thanks. I fixed this.
