### ISSUE TITLE
dependencies issue started appearing. 

### ISSUE THREAD

**Issue by narayananl23** [maxmind/GeoIP2-java#85]
The below issue was not there before two days.

Failed to execute goal on project ABC: Could not resolve dependencies for project com:war:1.0.0: Failed to collect dependencies at com.maxmind.geoip2:geoip2:jar:2.7.0 -> com.maxmind.db:maxmind-db:jar:1.2.1 -> com.fasterxml.jackson.core:jackson-databind:jar:2.9.0-SNAPSHOT: Failed to read artifact descriptor for com.fasterxml.jackson.core:jackson-databind:jar:2.9.0-SNAPSHOT: Could not find artifact com.fasterxml:oss-parent:pom:28

**Comment by stilford** [comment]
broke our builds as well

**Comment by oschwald** [comment]
Please upgrade to 2.8.1.

**Comment by narayananl23** [comment]
Thanks Oschwald,


but If I change to 2.8.1 it still errors. 

```
Caused by: org.springframework.beans.BeanInstantiationException: Could not instantiate bean class [com.esri.sms.services.proxy.MaxMindService]: Constructor threw exception; nested exception is java.lang.NoClassDefFoundError: org/apache/http/client/config/RequestConfig
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:163)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:87)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1006)

```
the below works when i update POM.. 
```
		<dependency>
			<groupId>com.maxmind.geoip2</groupId>
			<artifactId>geoip2</artifactId>
			<version>2.7.0</version>
			<exclusions>
            <exclusion>
                <groupId>com.fasterxml.jackson.core</groupId>
                <artifactId>jackson-databind</artifactId>
            </exclusion>
        </exclusions>		
        </dependency>  
```

**Comment by oschwald** [comment]
@narayananl23, that sounds like a separate issue. Would you open a ticket for it with more details about your environment and the output of `mvn dependency:tree -Dverbose` for your project?

**Comment by narayananl23** [comment]
Sure will do it.. i see the issue pop up on stackoverflow today for others as well

http://stackoverflow.com/questions/42386730/issue-with-maxmind-dependency

**Comment by oschwald** [comment]
@narayananl23, your original issue was fixed in the 2.8.1 release. The second issue appears to be unrelated based on the trace you posted.

**Comment by narayananl23** [comment]
@oschwald  will 2.8.1 will be added to this ? I only see 2.8.0.
https://mvnrepository.com/artifact/com.maxmind.geoip2/geoip2

**Comment by oschwald** [comment]
2.8.1 was released this morning through oss.sonatype.org. It may take a while for it to be available on all mirrors.

**Comment by narayananl23** [comment]
that may be the reason

when I add the dependency org.apache.httpcomponents.httpclient, the build worked for me..


```
<dependency>
			<groupId>com.maxmind.geoip2</groupId>
			<artifactId>geoip2</artifactId>
			<version>2.8.1</version>
        </dependency> 
        <!-- https://mvnrepository.com/artifact/org.apache.httpcomponents/httpclient -->
<dependency>
    <groupId>org.apache.httpcomponents</groupId>
    <artifactId>httpclient</artifactId>
    <version>4.5.3</version>
</dependency> 		

```

**Comment by stepio** [comment]
Could you please explain which dependency brought these SNAPSHOTs and how is it possible? We've missed half a day due to the such an error in multiple components. So we need to understand the root-cause and ways to prevent such cases in the future.

**Comment by stilford** [comment]
We lost 3 hours of development time across our entire team as a result of tracking this down as well.

**Comment by stepio** [comment]
Root cause was here:
```xml
    <groupId>com.maxmind.db</groupId>
    <artifactId>maxmind-db</artifactId>
    <version>1.2.1</version>

    <properties>
        <jackson-databind.version>[2.7.0,)</jackson-databind.version>
    </properties>
    <dependencies>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>${jackson-databind.version}</version>
        </dependency>
    </dependencies>
```
In latest versions fixed to:
```xml
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>2.7.9</version>
        </dependency>
```

**Comment by narayananl23** [comment]
How can i open a ticket ?  It creates many issues.
