### ISSUE TITLE
Is it necessary for comparing "database_type" with type name before reading databse

### ISSUE THREAD

**Issue by keefeleen** [maxmind/GeoIP2-java#87]
We found that before reading the database, the DatabaseReader class will compare database's metadata named "database_type" with the data type name we want (eg. "city"), if "database_type" doesn't contain the data type name, it will throw an exception and won't give the IP data we want.

I think the related code is as follows:

```
        String databaseType = this.getMetadata().getDatabaseType();
        if (!databaseType.contains(type)) {
            String caller = Thread.currentThread().getStackTrace()[2]
                    .getMethodName();
            throw new UnsupportedOperationException(
                    "Invalid attempt to open a " + databaseType
                            + " database using the " + caller + " method");
        }
```

Actually we want to know the exact purpose of adding this checking logic, and we also need to know the way to avoid failure when we do not want to use "city" or "country" in "database_type" while reading "city" or "country" information.

Thanks in advance and waiting for your reply.

**Comment by oschwald** [comment]
This is done in order to prevent people from using an incompatible database with a database-specific method, which leads to considerable confusion. I am not clear on exactly what you are trying to do, but generally you would not be able to successfully use a MaxMind database with a method other than the one with the right `database_type`. If you are creating your own database, I would suspect that you would want different model classes anyway.

**Comment by keefeleen** [comment]
@oschwald Thanks for your reply 😄

So, suppose we create a database with a "database_type" name "TestingDatabase". Since we do not have the string "City" in it，all the method designed for city level database cannot be read from it. Is that right?

**Comment by keefeleen** [comment]
@oschwald hi, sorry for bothering you again 😂

I need to confirm the question I listed above.

**Comment by keefeleen** [comment]
Let me elaborate the problem we are facing.

Our company is using Logstash geoip plugin to process data, which is using GeoIP2-java to extract data from db built by another team of our company with a fixed "database_type" named "ExampleLtd.". So, Logstash geoip plugin is not working then.

But, by using other libs, eg. MaxMind-DB-Reader-java, or perl, ruby's libs, data can be successfully read. Since the maintainer of Logstash geoip plugin would not change the lib they using now, can you help to solve this by removing the condition checking, may be just like MaxMind-DB-Reader-java :)

**Comment by oschwald** [comment]
@keefeleen, thanks for elaborating. I would suggest talking to the team in your company that builds the database. If you want the database to be compatible with any of our GeoIP2 readers, it should have a matching database type. As I mentioned previously, the check exists as it greatly reduces customer confusion and support requests on our side as it helps ensure people use the correct method with the correct database.

Another alternative, as you mention, would be to use `maxmind-db` directly. The `DatabaseReader` class isn't much more than a helper class to make integrations easier.
