### ISSUE TITLE
JDK6 Backport

### ISSUE THREAD

**Issue by stokito** [maxmind/GeoIP2-java#90]
I'm working on a big legacy project which works only with JDK6 and we can't upgrade to JDK7 for now.
So we can't use the GeoIP3 library because it's compiled and uses libraries for JDK7.
Could we downgrade a GeoIP library to JDK6?
From code respective the changes are minimal, the only one problem is a version of Jackson which is downgraded to 2.6.7 and this might cause a problems for those who used a Maven nearest dependency resolution.

I created a small fork with backport but work isn't finished yet.
https://github.com/stokito/GeoIP2-java/commit/3d59c219b298fc9a18a3a159158b558dd43664c3

If my work will be successful could you accept it and downgrade requirement to JDK6?

**Comment by oschwald** [comment]
We use features in the newer Jackson that are required by the MMDB reader to prevent data corruption. Rather that trying to backport the existing code to Java 6, I would recommend using the 2.7.0 release of this package.
