### ISSUE TITLE
is the WebServiceClient thread-safe or not ?

### ISSUE THREAD

**Issue by Kidlike** [maxmind/GeoIP2-java#91]
I'm a bit confused with this.

In the README, under the Country section, it says

```
// This creates a WebServiceClient object that can be reused across requests.
// The object is closeable and will keep connections alive for future
// requests.
```

But then in the example I would assume the implication is that it creates a new instance for each request.

```
try (WebServiceClient client = new WebServiceClient.Builder(42, "license_key")
        .build()) {
    ...
    CountryResponse response = client.country(ipAddress);
    ...
```

There is also a statement in the README, that _"This API fully supports use in multi-threaded applications"_. But which API? I would see the Database and Web Services as 2 different APIs.

I also found this PR, which makes me believe that at least the Web Service API is indeed Thread-Safe:
https://github.com/maxmind/GeoIP2-java/issues/70

---

So, I believe that it is indeed safe to concurrently call `WebServiceClient#country` on the same WebServiceClient object?

Can someone confirm this? And if so make it a bit more clear in the documentation? :)

**Comment by oschwald** [comment]
The client is thread safe. The example shows closing the client as it should be closed once you are done making requests (assuming you are done at some point).

**Comment by Kidlike** [comment]
It will never be done really. Except of course when the application shuts down.

Are there any concerns around not ever closing the client? (e.g. session/cookie timeouts or anything similar?)

**Comment by oschwald** [comment]
If your application continuously uses the client until it exits, there is no reason to close it explicitly.

**Comment by Kidlike** [comment]
Thanks for your help :)

What if there is a break of several hours between 2 requests ?

**Comment by oschwald** [comment]
If you expect a several hours break between requests, you may be better off closing the client after the request so that any open connections are closed immediately.

**Comment by Kidlike** [comment]
Thanks a lot for all the info!

I would suggest to add a bit more info inside the docs :)
