### ISSUE TITLE
Inconsistent regional breaks

### ISSUE THREAD

**Issue by ShinXinyuChen** [maxmind/GeoIP2-java#92]
Hi,

I recently found that the subdivision.getIsoCode() is giving me inconsistent regional breaks, thus limiting the ability to productionize pulls at a particular granularity. As an example, here are 2 IP addresses from Ireland, the first with city, county, province, country and continent all reported while the second is missing county:

[https://www.maxmind.com/en/geoip2-precision-demo?ip=51.171.227.59](https://www.maxmind.com/en/geoip2-precision-demo?ip=51.171.227.59)
The iso code returned from subdivision.getIsoCode() from is "TA" (Tipperary county), which is at province level. 
[https://www.maxmind.com/en/geoip2-precision-demo?ip=37.228.229.186](https://www.maxmind.com/en/geoip2-precision-demo?ip=37.228.229.186)
The iso code returned from subdivision.getIsoCode() is "L" (Leinster Province), which is at province level.

**Comment by oschwald** [comment]
This is not an issue with this library in particular. It is related to the data within the database. The database can have multiple ISO subdivision levels. In particular, it appears the first IP you have provided has two levels, one for County Tipperary and another for Munster. This library provides `getLeastSpecificSubdivision`, `getMostSpecificSubdivision`, and `getSubdivisions`. The last one returns all subdivisions for a record.

Given that this is a data issue and not a library issue, please send any follow-up questions to [support@maxmind.com](mailto:support@maxmind.com).
